apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-subchart
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: quarkus-subchart/
    repoURL: https://github.com/christianh814/gitops-examples
    targetRevision: master
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        path: quarkus-subchart/
        repoURL: https://github.com/christianh814/gitops-examples
        targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
